version: '3.5'

services:
  nifi-conf-loader:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - NIFI_UID
      - NIFI_GID
      - ADDITIONAL_LIBS_URLS
    networks:
      - kafka-net
    volumes:
      - nifi-conf-vol:/nifi-conf
      - nifi-additional-libs-vol:/additional-libs
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
        reservations:
          memory: 16M

networks:
  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    external: true

volumes:
  nifi-conf-vol:
    name: ${NIFI_CONF_VOL_NAME:-nifi-conf-vol}

  nifi-additional-libs-vol:
    name: ${NIFI_ADDITIONAL_LIBS_VOL_NAME:-nifi-additional-libs-vol}