version: '3.5'

services:
  nifi-loader:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/etl/nifi-loader}:${IMAGE_TAG:-latest}
    environment:
      NIFI_UID:
      NIFI_GID:
      ADDITIONAL_LIBS_URLS:
    networks:
      kafka-net:
    volumes:
      - nifi-conf-vol:/nifi-conf
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-16M}

networks:
  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    driver: ${KAFKA_NET_DRIVER:-overlay}
    external: true

volumes:
  nifi-conf-vol:
    name: ${NIFI_CONF_VOL_NAME:-nifi-conf-vol}
